# Generated by Django 2.2.2 on 2019-06-30 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_dog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
